[package]
name = "flappy-bird"
version = "0.1.0"
authors = ["someone-existing <haris.sinfo16@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra="0.6.1"
hecs="0.3.2"
rand="0.8.3"
